name: CI

on: [push]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go
      uses: actions/setup-go@v2.1.3
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        go get -u golang.org/x/lint/golint
        go list -f {{.Target}} golang.org/x/lint/golint

    - name: Lint
      run: /home/runner/go/bin/golint ./...
      
    - name: Test
      run: make test
    
    - name: Build Release Artifact
      run: |
        curl -sfL https://install.goreleaser.com/github.com/goreleaser/goreleaser.sh | sh
        ./bin/goreleaser --skip-publish --skip-validate --snapshot
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: dist
        path: dist
